accessing
refreshElements

	self elements: { 
		'name' -> self model name.
		'surname' -> self model surname.
		'number 1' -> self model number1.
		'number 2' -> self model number2.
		'scale' -> self model scale.
		'password' -> self model password.
		'rememberMe' -> self model rememberMe.
		'color' -> self model color.
		'date' -> self model date.
		'gender' -> self model gender.
		'items' -> self model selectedItems }